name: Admin Panel CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/jerthedev/admin-panel/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/jerthedev/admin-panel/**'

jobs:
  # PHP/Laravel Tests
  php-tests:
    name: PHP Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [11.x, 12.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug

      - name: Install dependencies
        run: |
          cd packages/jerthedev/admin-panel
          composer install --prefer-dist --no-progress

      - name: Run PHP tests
        run: |
          cd packages/jerthedev/admin-panel
          vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: packages/jerthedev/admin-panel/coverage.xml
          flags: php
          name: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}

  # JavaScript/Vue Tests
  js-tests:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/jerthedev/admin-panel/package-lock.json'

      - name: Install dependencies
        run: |
          cd packages/jerthedev/admin-panel
          npm ci

      - name: Run JavaScript tests
        run: |
          cd packages/jerthedev/admin-panel
          npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: packages/jerthedev/admin-panel/coverage/lcov.info
          flags: javascript
          name: javascript

  # Build and Package Tests
  build-tests:
    name: Build Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/jerthedev/admin-panel/package-lock.json'

      - name: Install dependencies
        run: |
          cd packages/jerthedev/admin-panel
          npm ci

      - name: Build assets
        run: |
          cd packages/jerthedev/admin-panel
          npm run build

      - name: Check build output
        run: |
          cd packages/jerthedev/admin-panel
          ls -la dist/
          # Verify critical files exist
          test -f dist/admin-panel.js
          test -f dist/admin-panel.css

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: packages/jerthedev/admin-panel/dist/
          retention-days: 7

  # Quick E2E Smoke Test
  smoke-test:
    name: E2E Smoke Test
    runs-on: ubuntu-latest
    needs: [php-tests, js-tests, build-tests]
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: admin_panel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/jerthedev/admin-panel/package-lock.json'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, mysql, pdo_mysql

      - name: Setup environment
        run: |
          cd packages/jerthedev/admin-panel
          cp ../../../.env.example ../../../.env
          echo "DB_CONNECTION=mysql" >> ../../../.env
          echo "DB_HOST=127.0.0.1" >> ../../../.env
          echo "DB_PORT=3306" >> ../../../.env
          echo "DB_DATABASE=admin_panel_test" >> ../../../.env
          echo "DB_USERNAME=root" >> ../../../.env
          echo "DB_PASSWORD=password" >> ../../../.env
          echo "ADMIN_PANEL_ALLOW_ALL=true" >> ../../../.env

      - name: Install dependencies
        run: |
          cd packages/jerthedev/admin-panel
          cd ../../../ && composer install --prefer-dist --no-progress
          cd packages/jerthedev/admin-panel && npm ci

      - name: Setup Laravel
        run: |
          cd packages/jerthedev/admin-panel
          cd ../../../
          php artisan key:generate
          php artisan migrate --force

      - name: Install Playwright
        run: |
          cd packages/jerthedev/admin-panel
          npx playwright install chromium

      - name: Build assets
        run: |
          cd packages/jerthedev/admin-panel
          npm run build

      - name: Start server and run smoke test
        run: |
          cd packages/jerthedev/admin-panel
          cd ../../../
          php artisan serve --port=8000 &
          sleep 5
          cd packages/jerthedev/admin-panel
          # Run just the critical tests
          npm run test:e2e -- --project=chromium --grep="should load admin panel test page|should redirect unauthenticated users to login"

  # Code Quality Checks
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          tools: phpstan, php-cs-fixer

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/jerthedev/admin-panel/package-lock.json'

      - name: Install dependencies
        run: |
          cd packages/jerthedev/admin-panel
          composer install --prefer-dist --no-progress
          npm ci

      - name: Run PHP CS Fixer
        run: |
          cd packages/jerthedev/admin-panel
          vendor/bin/pint --test

      - name: Run PHPStan
        run: |
          cd packages/jerthedev/admin-panel
          vendor/bin/phpstan analyse --no-progress

      - name: Run ESLint
        run: |
          cd packages/jerthedev/admin-panel
          npm run lint

      - name: Check TypeScript
        run: |
          cd packages/jerthedev/admin-panel
          npm run type-check
